FROM postgres:9.6.23

#zsh install
#RUN apt-get update
#RUN apt-get install -y wget git
#RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)"

#EXPOSE 5432
#RUN ["postgres"]